version: '2'

services:


    nginx:
      build: 
        context: ./nginx
        # args:
        #   - PHP_UPSTRAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
      ports:
        - "80:80"
        - "4433:443"
      volumes:
        - ./www:/usr/share/nginx/html
        - ./nginx/site:/etc/nginx/conf.d/
      tty: true
      dns:
          - 8.8.8.8
          - 114.114.114.114
      depends_on:
        - php-fpm
      networks:
        - backend
#FIREBUG  问题:了之前服务启动后只能访问静态文件,访问php 文件时服务提示file not found
#         原因:静态文件是放在 nginx 容器当中的,nginx 自然能访问到,而出现 php 文件的时候会通过 fastcgi 转发到 php-fpm 容器当中,php-fpm 容器没有对应的动态文件,自然是找不到
#         解决:nginx 和 php-fpm 两个容器共享同一个文件目录,在目录当中再做区分动静态文件,也就是说两个容器都来挂载相同的目录
    php-fpm:
        build:
          context: ./php-fpm
        volumes:
          - ./php-fpm/php71.ini:/user/local/etc/php/php.ini
          - ./www:/usr/share/nginx/html
        expose:
          - "9000"
        networks: 
          - backend

networks:
  # frontend:
  #   driver: "bridge"
  backend:
    driver: "bridge"